name: Lobby
main: org.Deniable.Lobby
version: ${version}
api-version: 1.13
author: Asylx

commands:
  spawn:
    description: Spawn command
  admin:
    description: Admin command
  gmc:
    description: Gamemode creative
  gms:
    description: Gamemode survival!